- package.json
adds precommit hook for prettier via husky and lint-staged. closes #61
> Add Prettier precommit hook

- Dockerfile
- circle.yml
- test/changePwd.spec.js
- test/setup-database.js
Adds a CircleCI build that pulls an image of Stardog 5 and burns a license and test data onto the image, then deploys the image on port 5820 and runs our jest tests against it.
> CircleCI integration tests

- lib/Connection.js
- lib/db.js
- lib/query/index.js
- lib/transaction.js
- test/createDB.spec.js
- test/dropDB.spec.js
- test/explain.spec.js
- test/exportDB.spec.js
- test/getNamespaces.spec.js
- test/getProperty.spec.js
- test/query.spec.js
- test/transactions.spec.js
Removed database as part of the connnection object. Updated tests.
Used currying in a few places to show how you could do it in user code.
> 🎨 - More API consistency

- .gitignore
- .npmignore
- lib/db.js
- lib/index.js
- lib/query/index.js
- package.json
- scripts/build.js
Add rollbar build script. Closes #49.
Cleaned up some stuff in .npmignore. Closes #59.
> 📦 - Add build system.

- lib/icv.js
- lib/index.js
- test/clearICV.spec.js
- test/convertICV.spec.js
- test/exportDB.spec.js
- test/fixtures/issues/constraints.ttl
- test/fixtures/issues/data.ttl
- test/fixtures/issues/schema.ttl
- test/getDB.spec.js
- test/getDBSize.spec.js
- test/getICV.spec.js
- test/getNamespaces.spec.js
- test/query.spec.js
- test/setICV.spec.js
- test/setup-database.js
Rewrites the (known-to-be-working) ICV methods, adds tests, relates to #75
> Port old ICV methods

- lib/query/index.js
- lib/query/stored.js
- lib/response-transforms.js
- test/stored.spec.js
Related to #85.
Added missing stored query APIs.
> ✨ - stored query APIs

- lib/db/main.js
- lib/index.d.ts
- lib/query/stored.js
- lib/user/main.js
- lib/user/role.js
- package.json
- test/deleteRole.spec.js
- test/deleteUser.spec.js
- test/exportDB.spec.js
- test/stored.spec.js
> Adds typescript declaration file.

- lib/Connection.js
- lib/db/icv.js
- lib/db/main.js
- lib/db/options.js
- lib/db/transaction.js
- lib/fetch.js
- lib/query/main.js
- lib/query/stored.js
- lib/server.js
- lib/user/main.js
- lib/user/role.js
- package.json
Was pointing to a non-existant file. Migrated to have a common place for the
fetch pony-fill. Removed include: credentials because I don't think we need it
> 🐛 - package.json bug

- lib/db/icv.js
- lib/index.d.ts
- scripts/docs.js
- test/query.spec.js
- test/transactions.spec.js
Also made incredibly minor changes like removing parameters that weren't used
> 📝 - Add a bunch of JSDoc for function parameters. Fix #97

- Dockerfile
- circle.yml
- lib/index.d.ts
- lib/user/main.js
- test/getUser.spec.js
adds user.get which retrieves all information on a given user
> get single user info

- lib/index.d.ts
- lib/user/main.js
- test/isUserValid.spec.js
adds `user.valid` which returns 200 if creds are valid, else 401
> user isValid

- lib/index.d.ts
- lib/query/main.js
- lib/query/utils.js
- test/query.spec.js
Closes #110
Closes #109
Also fixes bug where query string values were not properly being sent to the
server.
> ⚡️ - Expose mechanism to override accept header

- lib/index.d.ts
Needed to do these changes to the ts declarations in order to get my stuff to compile
> Corrected Body interface and db create signature

- README.md
Autogenerated docs after adding graphql, storedFunctions, versioning, and virtualGraph methods.
> Update docs for 1.0 release

- lib/Connection.js
- lib/db/graph.js
- lib/db/reasoning.js
- lib/index.d.ts
- lib/query/main.js
- test/Connection.spec.js
- test/query.spec.js
Includes tests and some small bits of re-formatting, as well.
> Allow custom headers, such as different auth headers (fix #150)

- .circleci/config.yml
- Dockerfile
- README.md
- test/query.spec.js
Resolves https://github.com/stardog-union/stardog.js/issues/183
CircleCI issue: https://circleci.com/gh/stardog-union/stardog.js/361?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> Update to version 6 and fix CircleCI

- test/graphql.spec.js
There are no changes to the source here, only tests verifying some existing functionality.
Requires https://github.com/stardog-union/stardog/pull/7063 to be merged upstream
> Explicitly test graphql explain support

- .circleci/config.yml
- Dockerfile
- README.md
- lib/db/icv.js
- lib/index.d.ts
- test/graphql.spec.js
- test/icv.spec.js
- test/query.spec.js
Close #187.
Fix #186.
This is PR'd against the `v2` branch, but once it's accepted, we can merge it into `master` as well.
> Add ICV report functionality and fix existing types

- README.md
- lib/index.d.ts
- lib/query/stored.js
- package-lock.json
- test/graphql.spec.js
- test/stored.spec.js
See the issue for context. This is required for https://github.com/stardog-union/stardog-studio/issues/926
> add support for `reasoning` and `description` attributes to stored queries

- Dockerfile
- README.md
- lib/db/options.js
- lib/index.d.ts
- scripts/build.js
- test/getDBOptions.spec.js
v2 version of https://github.com/stardog-union/stardog.js/pull/193 to avoid resolving conflicts between master and v2.
> add two endpoints for getting all db properties default values and getting all actual values and upgrade stardog to latest

- lib/db/main.js
Close #204 .
Note that this won't actually work with Stardog until https://github.com/stardog-union/stardog/pull/8296 is merged.
> Add ability to send properties file on db.create

- lib/db/main.js
- test/exportDB.spec.js
Close #210 .
Test failures are the expected failures for Stardog 7.x and stardog.js pre-v2 release.
Re-upping PR against the correct branch!
> Add support for streaming export data to file (and compression)

- README.md
- lib/index.d.ts
- lib/query/graphql.js
- test/graphql.spec.js
> Support updating GraphQL schemas without remove/add (with backwards compat)

- README.md
- lib/db/main.js
- lib/index.d.ts
> Add database model endpoint

- README.md
- lib/index.d.ts
- lib/virtualGraphs.js
> Add Virtual Graph List endpoint

- README.md
- lib/index.d.ts
- lib/virtualGraphs.js
> Add support for database constraint for virtual graphs

- README.md
- lib/dataSources.js
- lib/index.d.ts
close [STUD-517](https://stardog.atlassian.net/browse/STUD-517?atlOrigin=eyJpIjoiYWIwMWFlZGM1ZWQ1NDBlOTkwMWFiOThmNjMxNzI0YWYiLCJwIjoiaiJ9)
> [STUD-517] data hub - allow stardog.js to accept query params

- lib/db/docs.js
I haven't tested this.  I'm not sure where `add` is used.  This will resolve issue #255
> Update `new Buffer` to `Buffer.from(...)`

- .circleci/docker-compose.yml
- .circleci/jwt.yaml
- .circleci/token.properties
- .nvmrc
- Dockerfile
- lib/Connection.js
- lib/index.d.ts
- lib/user/main.js
- test/Connection.spec.js
- test/getUserToken.spec.js
- test/setup-database.js
- test/stored.spec.js
* Add user.token() command to fetch a jwt token
* Add support for using token for Authorization header
> [VET-867] feature: add token auth support

- README.md
- lib/db/icv.js
- lib/index.d.ts
- test/icv.spec.js
VET-1900
* ~~based on https://github.com/stardog-union/stardog.js/pull/267~~
* waiting for `3.4.0` release
* releasing `4.0.0` after this
> [VET-1900] Remove ICV add/remove

- README.md
- lib/dataSources.js
- lib/index.d.ts
- package.json
- test/dataSources.spec.js
VET-2029
* requires develop version of stardog (probably future v8.1.0)
> [VET-2029] Stardog.js changes for automapping service

- README.md
- lib/index.d.ts
- lib/user/main.js
- test/addUserRole.spec.js
- test/assignRole.spec.js
> Adding addRole to the user code

- .circleci/config.yml
consolidating var names across repos for better tracking/updating purposes
if ci passes then it works
> [VET-2901] rename env vars

- lib/fetch.js
VET-2824
Node 18 comes with its own (experimental) fetch global which doesn't play nice with FormData, so fallback to using our fetch polyfill if running in node
> [VET-2824] Compatibility with node 18

- README.md
- lib/db/main.js
- lib/index.d.ts
- test/listDBInfo.spec.js
> [VET-3070] add `db.listInfo`

- README.md
- lib/index.d.ts
- lib/query/utils.js
- test/queryUtils.spec.js
> [VET-3276] Add `Validate` to Stardog.js

- README.md
- lib/index.d.ts
- lib/user/main.js
- test/assignPermissionToUser.spec.js
- test/assignRole.spec.js
- test/changePwd.spec.js
- test/deletePermissionFromUser.spec.js
- test/deleteUser.spec.js
- test/isSuperUser.spec.js
- test/isUserEnabled.spec.js
- test/listUserEffPermissions.spec.js
- test/listUserInfo.spec.js
- test/listUserPermissions.spec.js
- test/setUserRoles.spec.js
- test/userEnabled.spec.js
- add url to `Response`
- update `user.create` to expect `user.username` (VET-2366)
> Stardog 9 updates

- README.md
- lib/catalog.js
- lib/index.d.ts
- lib/index.js
- package.json
- test/catalog.spec.js
> [VET-3627] Add support for catalog endpoints

- lib/db/namespaces.js
> [VET-4121] Avoid internal errors for bad namespace responses

- README.md
- lib/catalog.js
- lib/index.d.ts
VET-4197
No hurry to review/release since I can just use a local build 🤷
> [VET-4197] Add testConnection method for Knowledge Catalog

- README.md
- lib/catalog.js
- lib/index.d.ts
> [VET-3766][VET-4297] Update addCredentials to support Atlan and Purview
