stardog-union/stardog.js

- lib/user.js
- test/assignPermissionToUser.spec.js
- test/changePwd.spec.js
- test/deletePermissionFromUser.spec.js
- test/deleteUser.spec.js
- test/isSuperUser.spec.js
- test/isUserEnabled.spec.js
- test/listUserEffPermissions.spec.js
- test/listUserPermissions.spec.js
- test/setUserRoles.spec.js
- test/userEnabled.spec.js
Closes #70
Pass in name when creating both a user and a role.
> 🛁 - Update create arguments

- package.json
Adds postversion githook to generate updates to CHANGELOG.md with mdchangelog. Closes #60.
Depends on having github oauth token at `env.MDCHANGELOG_TOKEN`.
> Automate CHANGELOG

- .eslintrc.json
- lib/query/main.js
- lib/query/utils.js
- lib/response-transforms.js
- test/clearICV.spec.js
- test/dropDB.spec.js
- test/getDB.spec.js
- test/getICV.spec.js
- test/query.spec.js
Closes #88
Adds logic to handle update type queries. Users should be able to just call
query.execute regardless of what it is with this change.
> ✨ - Expose update endpoint

- lib/index.d.ts
Now has four top-level namespaces (`db`, `query`, `user`, `server`) and one class (`Connection`) instead of a global `stardog` namespace.
> Cleanup typedefs

- lib/db/options.js
...to prevent arrays from being flattened when configuring DB options
> add "safe" option to the dispatchDBOptions call to the flat library

- lib/index.d.ts
- lib/query/index.js
It'd be nice if I could just use the `queryType` method that already exists in stardog.js instead of writing my own method that maintains compatibility with it. This PR makes that happen. Any thoughts, @snowell or @tysoeh?
> Expose utils for use by consumers of Stardog.js

- lib/Connection.js
- lib/db/docs.js
- lib/db/graph.js
- lib/db/icv.js
- lib/db/main.js
- lib/db/options.js
- lib/db/reasoning.js
- lib/db/transaction.js
- lib/db/versioning.js
- lib/fetch.js
- lib/index.d.ts
- lib/query/graphql.js
- lib/query/main.js
- lib/query/stored.js
- lib/server.js
- lib/storedFunctions.js
- lib/user/main.js
- lib/user/role.js
- lib/virtualGraphs.js
- package.json
- test/Connection.spec.js
- test/queryList.spec.js
- test/reasoning.spec.js
When a user is behind a proxy that has a self-signed certificate, or is directly hitting an HTTPS endpoint that has a self-signed certificate, `node-fetch` (used by our `fetch-ponyfill` dependency in Node-like environments) will, by default, reject the request with a "self-signed certificate" error. This prevents using stardog.js in Node/Electron under some fairly common development scenarios. The way to work around this with `node-fetch` is to supply an 'agent' for requests that allows connections with self-signed certificates (see [here](https://github.com/bitinn/node-fetch/issues/19), for example). However, `fetch-ponyfill` doesn't allow you to supply an agent. So, this PR puts a thin wrapper around the ponyfill, and allows end users to supply a custom agent to stardog.js when a …
> Support fetch from behind proxies and/or to endpoints with self-signed certs

- lib/index.d.ts
- lib/query/main.js
- test/query.spec.js
Adds support, tests, and typings for `additionalHandlers` (currently only `onResponseStart`) on `query.execute`.
Closes #156.
> Allow providing "additionalHandlers" on query.execute

- .gitignore
- lib/db/index.js
- lib/db/main.js
- lib/db/namespaces.js
- lib/index.d.ts
- package-lock.json
- test/fixtures/namespace_import.ttl
- test/getNamespaces.spec.js
- test/importNamespaces.spec.js
I'm not sold on calling the method for importing namespaces "set", since it doesn't _completely replace_ existing namespaces, but it was nicer in terms of corresponding to "get". What "set" actually does, as the test's filename indicates, is _add_ or _overwrite existing_ namespaces by importing from an RDF file; it doesn't _set_ the namespaces to _exactly_ those specified (e.g., if there is an existing namespace "foo=whatever" in the DB on the server, and the contents sent over HTTP consist in namespaces "bar=baz" and "blah=blah", the namespaces in the DB on the server when all is said and done will be "foo=whatever", "bar=baz", and "blah=blah" -- "foo=whatever" is not removed).
Seems okay to call it "set", though.
> Add ability to import namespaces via string or file (new Stardog endpoints)

- .eslintrc.json
- lib/index.d.ts
- lib/query/main.js
- test/query.spec.js
By allowing `onResponseStart` to optionally return `false` (telling stardog.js that it should not continue processing the response itself), all processing of the Stardog response can be effectively "turned over" to the caller. This allows, for example, the caller to _stream_ the response without ever having `response.json()` (or some other response accumulator that stardog.js might call) being called on it by stardog.js.
> Allow `onResponseStart` to abort further stardog.js processing

- lib/db/namespaces.js
- lib/db/options.js
- lib/index.d.ts
Test failures are all the expected ones for Stardog 7.
> Make old-style namespaces request actually get only the namespaces (fix #207)

- lib/query/utils.js
- test/queryUtils.spec.js
We need to remove comments (and base) _before_ prefix information is removed; this was an error that we fixed in the TypeScript branch and now need to port back here. Doing things in this order actually [matches the Stardog behavior](https://github.com/stardog-union/stardog/blob/886cdbcd251082a207fbeae53a0ff1abf1c9e8b2/utils/rdf/main/src/com/complexible/common/rdf/query/SPARQLUtil.java#L155-L190).
> Handle commented-out prefix lines in queries (fix #228)

- README.md
- lib/index.d.ts
- lib/query/graphql.js
See https://github.com/stardog-union/stardog.js/tree/v2#additionalhandlers (currently only used by query.execute)
> Allow graphql.execute to accept additionalHandlers

- README.md
- lib/dataSources.js
- lib/index.d.ts
- lib/index.js
- test/dataSources.spec.js
- test/fixtures/data_source_metadata.ttl
[STUD-528]
You can run the full test suite by removing the `describe.only` as long as you have a running MySQL server with an empty password for the root user on port 3306 (default for MySQL) and the [JDBC Driver for MySQL](https://dev.mysql.com/downloads/connector/j/) in copied into your `stardog_install_dir/server/dbms/` (see [Stardog Manual](https://www.stardog.com/docs/#_configuration)).
[STUD-528]: https://stardog.atlassian.net/browse/STUD-528
> [STUD-528] Add Data Sources

- Dockerfile
- README.md
- lib/dataSources.js
- lib/index.d.ts
- package-lock.json
VET-1472
* added `query` data-source method
* added other (missing) data-source methods as well:
* refreshCounts
* refreshMetadata
> [VET-1472] Implement new data source query API in stardog.js

- lib/Connection.js
otherwise we use the string `"undefined"` for the password
> use empty string for password if it is `undefined`

- lib/index.d.ts
- lib/user/main.js
- package.json
- test/whoAmI.spec.js
> [VET-1380] Add `admin/status/whoami` to Stardog.js

- README.md
- lib/dataSources.js
- lib/index.d.ts
VET-1703
Adds new endpoint to get data source type descriptions; LMK if I should undo Prettier's changes to README.md
> [VET-1703] Data source description endpoint

- package-lock.json
- package.json
[VET-2486](https://stardog.atlassian.net/browse/VET-2486)
For proper parsing of db properties that share the start of their name with the full name of another property (ex: `security.properties.sensitive` vs `security.properties.sensitive.groups`
see diff: https://github.com/hughsk/flat/compare/v2.0.1...5.0.2
> [VET-2486] Update flat package

- README.md
- lib/db/options.js
- test/getDBOptions.spec.js
[VET-2546](https://stardog.atlassian.net/browse/VET-2546)
> [VET-2546] **Breaking Change** Do not flatten request body nor unflatten response body for `db.options`

- README.md
- lib/db/icv.js
- lib/index.d.ts
- test/icv.spec.js
Re-adding deprecated methods to support applications that are expected to connect to multiple Stardog versions (i.e. Studio)
> Re-add deprecated icv methods

- README.md
- lib/dataSources.js
- lib/index.d.ts
- package.json
With the platform API change, we need to support sending JSON to the query endpoint
> [VET-2689] Add support for data source query options

- README.md
- lib/index.d.ts
- lib/query/stored.js
- test/stored.spec.js
VET-2831
* ~~now using the jsonld style because the json type is deprecated in stardog, and doesn't return or accept annotations~~
* removed the `params` args; what was this even used for?
in order to return the extra fields on stored queries you have to change `accept` on `stored.list` to use something besides json:
```js
stored.list(conn, { accept: 'application/ld+json' });
```
but note that this now returns jsonld and not simple json!
> [VET-2831] Update Stardog.js to allow arbitrary metadata for stored queries

- README.md
- lib/index.d.ts
- lib/user/main.js
- test/changePwd.spec.js
VET-5579
tests will pass once Stardog 11.1.0 is released
> [VET-5579] require current password for changing passwords
